name: coreJS Documentation
encoding: utf-8

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
pygments: true
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'http://corejs.docs.bqws.io/index.html'
author:         'bq'
root: '/'